services:
  react-leaflet:
    container_name: react-leaflet-dev
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4173:4173"
    volumes:
      - ./:/app/
