// CREATE
export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
// READ
export const READ_ORGANIZATION = "READ_ORGANIZATION";
// UPDATE
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
// DELETE
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
